application: vpcsim
version: 2
runtime: python
api_version: 2
threadsafe: false

handlers:
- url: /images
  static_dir: images

- url: /static/lib
  static_dir: static/lib
  mime_type: text/javascript

- url: /.*
  script: VPCsim-parameters.py
