application: vpcsim
version: 2
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /images
  static_dir: images

- url: /static/lib
  static_dir: static/lib
  mime_type: text/javascript

- url: /.*
  script: VPCsim-parameters.py

libraries:
- name: webapp2
  version: "2.5.2"
