application: vpcsim
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images

- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml

- url: /static/lib
  static_dir: static/lib
  mime_type: text/javascript

- url: /.*
  script: VPCsim-parameters.py


